// borrowed from the lwc-recipes project
const { jestConfig } = require('@salesforce/sfdx-lwc-jest/config');
jestConfig.testPathIgnorePatterns = [...jestConfig.testPathIgnorePatterns, "<rootDir>/stryker-tmp/"]; // added to keep jest from testing temp stryker folders
module.exports = {
  ...jestConfig,
  testTimeout: 10000,
  collectCoverageFrom: [
    "force-app/main/default/lwc/**/*.js",
    "!force-app/main/default/lwc/checkBrowser/*",
    "!force-app/main/default/lwc/checkBrowser/**/*",
    "!**/node_modules/**",
    "!**/__data__/**" // exclude js files used to generate test data
  ],
  coveragePathIgnorePatterns: [
    "force-app/main/default/lwc/policyActions/actions.js",
    "force-app/main/default/lwc/policyActions/roles.js",
    "force-app/main/default/lwc/policyDetailsOverview/buildInsuredData.js",
    "force-app/main/default/lwc/campaignUtilities/campaignUtilities.js"
    ],
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 85,
      statements: 85,
    },
    'force-app/main/default/lwc/**/*.js': {
      branches: 100,
      functions: 100,
      lines: 85,
      statements: 85,
    },
  },
  moduleNameMapper: {
    '^@salesforce/apex$': '<rootDir>/force-app/test/jest-mocks/apex',
    '^c/claimCommonJS$': '<rootDir>/force-app/test/jest-mocks/c/claimCommonJS/claimCommonJS',
    '^c/claimPaginator$': '<rootDir>/force-app/test/jest-mocks/c/claimPaginator/claimPaginator',
    '^c/claimDatatableObjectLink$': '<rootDir>/force-app/test/jest-mocks/c/claimDatatableObjectLink/claimDatatableObjectLink',
    '^c/claimDatatableCheckbox$': '<rootDir>/force-app/test/jest-mocks/c/claimDatatableCheckbox/claimDatatableCheckbox',
    '^c/claimDatatableCallHistory$': '<rootDir>/force-app/test/jest-mocks/c/claimDatatableCallHistory/claimDatatableCallHistory',
    '^c/claimDatatableUrl$': '<rootDir>/force-app/test/jest-mocks/c/claimDatatableUrl/claimDatatableUrl',
    '^c/emailButton$': '<rootDir>/force-app/test/jest-mocks/c/emailButton/emailButton',
    '^c/claimEmail$': '<rootDir>/force-app/test/jest-mocks/c/claimEmail/claimEmail',
    '^c/paginationDataTable$': '<rootDir>/force-app/test/jest-mocks/c/paginationDataTable/paginationDataTable',
    '^c/campaignMemberDatatable$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberDatatable/campaignMemberDatatable',
    '^c/campaignMemberActions$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberActions/campaignMemberActions',
    '^c/policyDetailsInsuranceToValue$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsInsuranceToValue/policyDetailsInsuranceToValue',
    '^c/policyDetailsToofReinstatement$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsToofReinstatement/policyDetailsToofReinstatement',
    '^c/policyDetailsToofReinstatement/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsToofReinstatement/__mocks__/policyDetailsToofReinstatement',
    '^c/billingLobInfoHover$': '<rootDir>/force-app/test/jest-mocks/c/billingLobInfoHover/billingLobInfoHover',
    '^c/billingButtonSfBilling$': '<rootDir>/force-app/test/jest-mocks/c/billingButtonSfBilling/billingButtonSfBilling',
    '^c/billingButtonSfBilling/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/billingButtonSfBilling/__mocks__/billingButtonSfBilling',
    '^c/policySummaryFieldHover$': '<rootDir>/force-app/test/jest-mocks/c/policySummaryFieldHover/policySummaryFieldHover',
    '^c/policyDetailsPremiumAdjustments$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsPremiumAdjustments/policyDetailsPremiumAdjustments',
    '^c/policyDetailsPremiumAdjustments/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsPremiumAdjustments/__mocks__/policyDetailsPremiumAdjustments',
    '^c/policyDetailsRating$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsRating/policyDetailsRating',
    '^c/policyDetailsRating/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsRating/__mocks__/policyDetailsRating',
    '^c/billingStatus$': '<rootDir>/force-app/test/jest-mocks/c/billingStatus/billingStatus',
    '^c/policyDetailsDssDiscount$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsDssDiscount/policyDetailsDssDiscount',
    '^c/policyDetailsDssDiscount/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsDssDiscount/__mocks__/policyDetailsDssDiscount',
    '^c/billingButtonSfpp$': '<rootDir>/force-app/test/jest-mocks/c/billingButtonSfpp/billingButtonSfpp',
    '^c/billingButtonSfpp/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/billingButtonSfpp/__mocks__/billingButtonSfpp',
    '^c/policySummaryRiskHover$': '<rootDir>/force-app/test/jest-mocks/c/policySummaryRiskHover/policySummaryRiskHover',
    '^c/billingTable$': '<rootDir>/force-app/test/jest-mocks/c/billingTable/billingTable',
    '^c/policyDetailsCommonJS$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsCommonJS/policyDetailsCommonJS',
    '^c/policyDetailsCoverage$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsCoverage/policyDetailsCoverage',
    '^c/policyDetailsCoverage/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsCoverage/__mocks__/policyDetailsCoverage',
    '^c/policyDetailsLabeledField$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsLabeledField/policyDetailsLabeledField',
    '^c/policyDetailsPapSchedule$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsPapSchedule/policyDetailsPapSchedule',
    '^c/policyDetailsVehicle$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsVehicle/policyDetailsVehicle',
    '^c/policyDetailsVehicle/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsVehicle/__mocks__/policyDetailsVehicle',
    '^c/policySummaryLobIcon$': '<rootDir>/force-app/test/jest-mocks/c/policySummaryLobIcon/policySummaryLobIcon',
    '^c/campaignMemberPolicyNumberDisplay$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberPolicyNumberDisplay/campaignMemberPolicyNumberDisplay',
    '^c/simpleConversationRowDisplay$': '<rootDir>/force-app/test/jest-mocks/c/simpleConversationRowDisplay/simpleConversationRowDisplay',
    '^c/simpleConversationRowDisplay/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/simpleConversationRowDisplay/__mocks__/simpleConversationRowDisplay',
    '^c/accountAlertRowDisplay$': '<rootDir>/force-app/test/jest-mocks/c/accountAlertRowDisplay/accountAlertRowDisplay',
    '^c/accountAlertRowDisplay/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/accountAlertRowDisplay/__mocks__/accountAlertRowDisplay',
    '^c/taskRowDisplay$': '<rootDir>/force-app/test/jest-mocks/c/taskRowDisplay/taskRowDisplay',
    '^c/taskRowDisplay/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/taskRowDisplay/__mocks__/taskRowDisplay',
    '^c/caseRowDisplay$': '<rootDir>/force-app/test/jest-mocks/c/caseRowDisplay/caseRowDisplay',
    '^c/caseRowDisplay/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/caseRowDisplay/__mocks__/caseRowDisplay',
    '^c/sobjectRowDisplay$': '<rootDir>/force-app/test/jest-mocks/c/sobjectRowDisplay/sobjectRowDisplay',
    '^c/sobjectRowDisplay/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/sobjectRowDisplay/__mocks__/sobjectRowDisplay',
    '^c/sObjectRowDisplayRow$': '<rootDir>/force-app/test/jest-mocks/c/sObjectRowDisplayRow/sObjectRowDisplayRow',
    '^c/sObjectRowDisplayRow/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/sObjectRowDisplayRow/__mocks__/sObjectRowDisplayRow',
    '^c/sortedDatatable$': '<rootDir>/force-app/test/jest-mocks/c/sortedDatatable/sortedDatatable',
    '^c/opportunityRowDisplay$': '<rootDir>/force-app/test/jest-mocks/c/opportunityRowDisplay/opportunityRowDisplay',
    '^c/opportunityRowDisplay/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/opportunityRowDisplay/__mocks__/opportunityRowDisplay',
    '^c/campaignMemberTabset$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberTabset/campaignMemberTabset',
    '^c/campaignMemberTabset/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberTabset/__mocks__/campaignMemberTabset',
    '^c/sobjectLinkAndHover$': '<rootDir>/force-app/test/jest-mocks/c/sobjectLinkAndHover/sobjectLinkAndHover',
    '^c/stopCampaignDirectMailers$': '<rootDir>/force-app/test/jest-mocks/c/stopCampaignDirectMailers/stopCampaignDirectMailers',
    '^c/checkboxGroupSelectionForm$': '<rootDir>/force-app/test/jest-mocks/c/checkboxGroupSelectionForm/checkboxGroupSelectionForm',
    '^c/checkboxGroupSelectionForm/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/checkboxGroupSelectionForm/__mocks__/checkboxGroupSelectionForm',
    '^c/modal$': '<rootDir>/force-app/test/jest-mocks/c/modal/modal',
    '^c/modal/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/modal/__mocks__/modal',
    '^c/caseJourneyPreviewData$': '<rootDir>/force-app/test/jest-mocks/c/caseJourneyPreviewData/caseJourneyPreviewData',
    '^c/caseJourneyPreviewData/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/caseJourneyPreviewData/__mocks__/caseJourneyPreviewData',
    '^c/userUtilities$': '<rootDir>/force-app/test/jest-mocks/c/userUtilities/userUtilities',
    '^c/assignToInput$': '<rootDir>/force-app/test/jest-mocks/c/assignToInput/assignToInput',
    '^c/assignToInputByAlpha$': '<rootDir>/force-app/test/jest-mocks/c/assignToInputByAlpha/assignToInputByAlpha',
    '^c/assignToInputByNumber$': '<rootDir>/force-app/test/jest-mocks/c/assignToInputByNumber/assignToInputByNumber',
    '^c/campaignMemberBulkAssignToModal$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberBulkAssignToModal/campaignMemberBulkAssignToModal',
    '^c/bulkAssignTo$': '<rootDir>/force-app/test/jest-mocks/c/bulkAssignTo/bulkAssignTo',
    '^c/bulkAssignTo/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/bulkAssignTo/__mocks__/bulkAssignTo',
    '^c/sfConnectCampaignMemberModal$': '<rootDir>/force-app/test/jest-mocks/c/sfConnectCampaignMemberModal/sfConnectCampaignMemberModal',
    '^c/campaignUtilities$': '<rootDir>/force-app/test/jest-mocks/c/campaignUtilities/campaignUtilities',
    '^c/campaignMemberRelatedListOptions$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberRelatedListOptions/campaignMemberRelatedListOptions',
    '^c/campaignMemberRelatedListOptions/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/campaignMemberRelatedListOptions/__mocks__/campaignMemberRelatedListOptions',
    '^c/userQuery$': '<rootDir>/force-app/test/jest-mocks/c/userQuery/userQuery',
    '^c/signedWrittenConsentQuickActionCalculations$': '<rootDir>/force-app/test/jest-mocks/c/signedWrittenConsentQuickActionCalculations/signedWrittenConsentQuickActionCalculations',
    '^c/checkboxGroupForm$': '<rootDir>/force-app/test/jest-mocks/c/checkboxGroupForm/checkboxGroupForm',
    '^c/checkboxGroupForm/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/checkboxGroupForm/__mocks__/checkboxGroupForm',
    '^c/caseSelection$': '<rootDir>/force-app/test/jest-mocks/c/caseSelection/caseSelection',
    '^c/taskStepPreviewTable$': '<rootDir>/force-app/test/jest-mocks/c/taskStepPreviewTable/taskStepPreviewTable',
    '^c/taskStepPreviewTable/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/taskStepPreviewTable/__mocks__/taskStepPreviewTable',
    '^c/signedWrittenConsentEndDateCalculation$': '<rootDir>/force-app/test/jest-mocks/c/signedWrittenConsentEndDateCalculation/signedWrittenConsentEndDateCalculation',
    '^c/caseCreateEdit$': '<rootDir>/force-app/test/jest-mocks/c/caseCreateEdit/caseCreateEdit',
    '^c/changeEventInputText$': '<rootDir>/force-app/test/jest-mocks/c/changeEventInputText/changeEventInputText',
    '^c/changeEventInputText/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/changeEventInputText/__mocks__/changeEventInputText',
    '^c/campaignAction$': '<rootDir>/force-app/test/jest-mocks/c/campaignAction/campaignAction',
    '^c/campaignConstants$': '<rootDir>/force-app/test/jest-mocks/c/campaignConstants/campaignConstants',
    '^c/campaignFollowUp$': '<rootDir>/force-app/test/jest-mocks/c/campaignFollowUp/campaignFollowUp',
    '^c/campaignQuery$': '<rootDir>/force-app/test/jest-mocks/c/campaignQuery/campaignQuery',
    '^c/campaignStartStopJourneyButton$': '<rootDir>/force-app/test/jest-mocks/c/campaignStartStopJourneyButton/campaignStartStopJourneyButton',
    '^c/campaignStartStopJourneyButton/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/campaignStartStopJourneyButton/__mocks__/campaignStartStopJourneyButton',
    '^c/clickToDial$': '<rootDir>/force-app/test/jest-mocks/c/clickToDial/clickToDial',
    '^c/dynamicProgressIndicator$': '<rootDir>/force-app/test/jest-mocks/c/dynamicProgressIndicator/dynamicProgressIndicator',
    '^c/dynamicProgressIndicator/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/dynamicProgressIndicator/__mocks__/dynamicProgressIndicator',
    '^c/journeyDateValidation$': '<rootDir>/force-app/test/jest-mocks/c/journeyDateValidation/journeyDateValidation',
    '^c/journeyOptIn$': '<rootDir>/force-app/test/jest-mocks/c/journeyOptIn/journeyOptIn',
    '^c/journeyPreviewData$': '<rootDir>/force-app/test/jest-mocks/c/journeyPreviewData/journeyPreviewData',
    '^c/lwcPaginator$': '<rootDir>/force-app/test/jest-mocks/c/lwcPaginator/lwcPaginator',
    '^c/messageServiceHelper$': '<rootDir>/force-app/test/jest-mocks/c/messageServiceHelper/messageServiceHelper',
    '^c/picklistValues$': '<rootDir>/force-app/test/jest-mocks/c/picklistValues/picklistValues',
    '^c/picklistValues/__mocks__$': '<rootDir>/force-app/test/jest-mocks/c/picklistValues/__mocks__/picklistValues',
    '^c/picklistValuesHelper$': '<rootDir>/force-app/test/jest-mocks/c/picklistValuesHelper/picklistValuesHelper',
    '^c/clickToDialPreference$': '<rootDir>/force-app/test/jest-mocks/c/clickToDialPreference/clickToDialPreference',
    '^c/notificationPreferencesError$': '<rootDir>/force-app/test/jest-mocks/c/notificationPreferencesError/notificationPreferencesError',
    '^c/notificationOptionSelection$': '<rootDir>/force-app/test/jest-mocks/c/notificationOptionSelection/notificationOptionSelection',
    '^c/lWC_NewOppLobProductSelection$': '<rootDir>/force-app/test/jest-mocks/c/lWC_NewOppLobProductSelection/lWC_NewOppLobProductSelection',
    '^c/checkboxGroupReusable$': '<rootDir>/force-app/test/jest-mocks/c/checkboxGroupReusable/checkboxGroupReusable',
    '^c/lWC_NewOppWorkSpaceAPI$': '<rootDir>/force-app/test/jest-mocks/c/lWC_NewOppWorkSpaceAPI/lWC_NewOppWorkSpaceAPI',
    '^c/confettiComponent$': '<rootDir>/force-app/test/jest-mocks/c/confettiComponent/confettiComponent',
    '^c/accountPPOPopup$': '<rootDir>/force-app/test/jest-mocks/c/accountPPOPopup/accountPPOPopup',
    '^c/datatablePicklist$': '<rootDir>/force-app/test/jest-mocks/c/datatablePicklist/datatablePicklist',
    '^c/accountEmailPopUp$': '<rootDir>/force-app/test/jest-mocks/c/accountEmailPopUp/accountEmailPopUp',
    '^c/accountCreateEditButtons$': '<rootDir>/force-app/test/jest-mocks/c/accountCreateEditButtons/accountCreateEditButtons',
    '^c/datatableToggle$': '<rootDir>/force-app/test/jest-mocks/c/datatableToggle/datatableToggle',
    '^c/accountAddressPopUp$': '<rootDir>/force-app/test/jest-mocks/c/accountAddressPopUp/accountAddressPopUp',
    '^c/accountCreateEditImport$': '<rootDir>/force-app/test/jest-mocks/c/accountCreateEditImport/accountCreateEditImport',
    '^c/agentQueueDataProvider$': '<rootDir>/force-app/test/jest-mocks/c/agentQueueDataProvider/agentQueueDataProvider',
    '^c/manageHouseholdMembersDatatable$': '<rootDir>/force-app/test/jest-mocks/c/manageHouseholdMembersDatatable/manageHouseholdMembersDatatable',
    '^c/fuzzySearch$': '<rootDir>/force-app/test/jest-mocks/c/fuzzySearch/fuzzySearch',
    '^c/checkBrowser$': '<rootDir>/force-app/test/jest-mocks/c/checkBrowser/checkBrowser',
    '^c/checkFeatureAccess$': '<rootDir>/force-app/test/jest-mocks/c/checkFeatureAccess/checkFeatureAccess',
    '^./onClickAccountForCti$': '<rootDir>/force-app/test/jest-mocks/c/onClickAccountForCti/onClickAccountForCti',
    '^c/policyDetailsCommonCSS$': '<rootDir>/force-app/test/jest-mocks/c/policyDetailsCommonCSS/policyDetailsCommonCSS.css',
    '^c/agentQueueCommonCSS$': '<rootDir>/force-app/test/jest-mocks/c/agentQueueCommonCSS/agentQueueCommonCSS.css',
    '^c/campaignCreateUtility$': '<rootDir>/force-app/test/jest-mocks/c/campaignCreateUtility/campaignCreateUtility',
    '^lightning/messageService$': '<rootDir>/force-app/test/jest-mocks/lightning/messageService',
    '^lightning/navigation$':
      '<rootDir>/force-app/test/jest-mocks/lightning/navigation',
      '^lightning/empApi$':
          '<rootDir>/force-app/test/jest-mocks/lightning/empApi',
    '^lightning/platformShowToastEvent$':
      '<rootDir>/force-app/test/jest-mocks/lightning/platformShowToastEvent',
    '^lightning/platformResourceLoader$':
      '<rootDir>/force-app/test/jest-mocks/lightning/platformResourceLoader',
    '^lightning/uiRecordApi$':
      '<rootDir>/force-app/test/jest-mocks/lightning/uiRecordApi',
    '^lightning/uiRelatedListApi$':
      '<rootDir>/force-app/test/jest-mocks/lightning/uiRelatedListApi',
    '^lightning/datatable$':
      '<rootDir>/force-app/test/jest-mocks/lightning/datatable/datatable',
    '^lightning/actions$':
      '<rootDir>/force-app/test/jest-mocks/lightning/actions',
    '^c/(.*)': '<rootDir>/force-app/main/default/lwc/$1/$1.js', // added to help stryker find classes under test
    '^lightning/modal$': '<rootDir>/force-app/test/jest-mocks/lightning/modal',//added for the modal
    '^lightning/modalHeader$': '<rootDir>/force-app/test/jest-mocks/lightning/modalHeader',
    '^lightning/modalBody$': '<rootDir>/force-app/test/jest-mocks/lightning/modalBody',
    '^lightning/modalFooter$': '<rootDir>/force-app/test/jest-mocks/lightning/modalFooter',
    '^lightning/flowSupport$': '<rootDir>/force-app/test/jest-mocks/lightning/flowSupport',

  },
  testPathIgnorePatterns: [
    "/__data__/" // exclude js files used to generate test data
  ]
};
